/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Services.ServicioCampeonato;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author y
 */
public class VentanaRegistrarPartido extends javax.swing.JFrame {

    private ServicioCampeonato servicio;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistrarPartido.class.getName());

    /**
     * Creates new form VentanaRegistrarPartido
     */
    public VentanaRegistrarPartido() {
        // 1. Inicializamos el servicio de campeonato inmediatamente al construir la ventana
        this.servicio = new ServicioCampeonato();

        // 2. Cargamos los componentes visuales de NetBeans
        initComponents();
        this.setLocationRelativeTo(null); // centrar pantalla
        // 3. ESTABLECER TÍTULO E ÍCONO EN LA BARRA DE CABECERA
        setTitle("FutMJI");
        try {
            // Buscamos la imagen en tus recursos
            java.net.URL urlIcono = getClass().getResource("/Vista/logo.png");
            if (urlIcono != null) {
                ImageIcon icon = new ImageIcon(urlIcono);
                // Cambiamos el icono nativo de la ventana
                setIconImage(icon.getImage());
            }
        } catch (Exception e) {
            System.out.println("No se pudo cargar el icono de la cabecera: " + e.getMessage());
        }
        // 3. Poblamos los datos y estética
        cargarEquiposEnCombos();
        colocarLogo();

    }

    private void colocarLogo() {
        try {
            // 1. Buscamos la ruta absoluta del recurso usando el paquete Vista
            java.net.URL stream = getClass().getResource("/Vista/logo.png");

            if (stream != null) {
                ImageIcon imagenOriginal = new ImageIcon(stream);

                // 2. Tomamos el tamaño exacto que le diste al cuadro naranja en el diseño
                int ancho = lblLogo.getWidth();
                int alto = lblLogo.getHeight();

                // Forzamos un tamaño ideal para el escudo en la parte superior
                if (ancho == 0 || alto == 0) {
                    ancho = 110;
                    alto = 110;
                }

                // 3. Escalamos la imagen para que rellene tu cuadro de forma perfecta
                Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                ImageIcon logoFinal = new ImageIcon(imagenEscalada);

                // 4. Asignamos la imagen, la traemos al frente y repintamos el componente
                lblLogo.setIcon(logoFinal);
                lblLogo.repaint();

            } else {
                System.out.println("No se pudo encontrar el archivo logo.png dentro del paquete Vista.");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar el logo en pantalla: " + e.getMessage());
        }
    }

    private void cargarEquiposEnCombos() {
        // 1. Limpiamos por completo los datos genéricos del diseñador visual
        cbEquipo1.removeAllItems();
        cbEquipo2.removeAllItems();

        try {
            // 2. Inicializamos el servicio si llega a estar en null para evitar errores
            if (servicio == null) {
                servicio = new ServicioCampeonato();
            }

            // 3. Recuperamos la lista de objetos Equipo cargados desde tu archivo .properties
            java.util.ArrayList<Entities.Equipo> listaEquipos = servicio.getEquipos();

            // 4. Recorremos las entidades y agregamos sus nombres reales a los JComboBox
            if (listaEquipos != null && !listaEquipos.isEmpty()) {
                for (Entities.Equipo eq : listaEquipos) {
                    cbEquipo1.addItem(eq.getNombre());
                    cbEquipo2.addItem(eq.getNombre());
                }
            } else {
                cbEquipo1.addItem("Sin equipos en archivo");
                cbEquipo2.addItem("Sin equipos en archivo");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al leer los equipos del archivo real: " + e.getMessage(),
                    "Error de Carga", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRegistrarEquipo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbEquipo1 = new javax.swing.JComboBox<>();
        txtGoles1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEquipo2 = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGoles2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 42, 86));

        btnInicio.setBackground(new java.awt.Color(25, 42, 86));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(225, 225, 225));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnRegistrarEquipo.setBackground(new java.awt.Color(25, 42, 86));
        btnRegistrarEquipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarEquipo.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrarEquipo.setText("Registrar Equipo");
        btnRegistrarEquipo.setBorder(null);
        btnRegistrarEquipo.setBorderPainted(false);
        btnRegistrarEquipo.setContentAreaFilled(false);
        btnRegistrarEquipo.addActionListener(this::btnRegistrarEquipoActionPerformed);

        btnSalir.setBackground(new java.awt.Color(25, 42, 86));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Cerrar sesion");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnInicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnRegistrarEquipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnSalir)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnInicio)
                .addGap(73, 73, 73)
                .addComponent(btnRegistrarEquipo)
                .addGap(76, 76, 76)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 246, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRAR PARTIDOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 42, 86));
        jLabel2.setText("Equipo Local");

        cbEquipo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbEquipo1.setForeground(new java.awt.Color(25, 42, 86));
        cbEquipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEquipo1.setBorder(null);
        cbEquipo1.addActionListener(this::cbEquipo1ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 42, 86));
        jLabel3.setText("Equipo Visitante");

        cbEquipo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbEquipo2.setForeground(new java.awt.Color(25, 42, 86));
        cbEquipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEquipo2.setBorder(null);

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(25, 42, 86));
        btnGuardar.setText("Guardar Partido");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("VS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 42, 86));
        jLabel5.setText("FutMJI");

        txtGoles2.addActionListener(this::txtGoles2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtGoles1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtGoles2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGoles1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGoles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // 1. Creamos la instancia de la tabla de posiciones (Ventana Principal)
        VentanaPrincipal principal = new VentanaPrincipal();

        // 2. La centramos en la pantalla para que no aparezca en una esquina
        principal.setLocationRelativeTo(null);

        //3. La hacemos visible para el usuario
        principal.setVisible(true);

        // 4. Cerramos la ventana actual de registro para liberar memoria
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void cbEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEquipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEquipo1ActionPerformed

    private void txtGoles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGoles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGoles2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. Capturamos los nombres seleccionados en la interfaz gráfica
        String nombreLocal = cbEquipo1.getSelectedItem().toString();
        String nombreVisitante = cbEquipo2.getSelectedItem().toString();

        // Validación 1: Evitar que un equipo juegue contra sí mismo
        if (nombreLocal.equals(nombreVisitante)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Un equipo no puede jugar contra sí mismo en el mismo partido.",
                    "Error de Selección", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación 2: Verificar que las cajas de texto no estén vacías
        if (txtGoles1.getText().trim().isEmpty() || txtGoles2.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, ingresa los goles de ambos equipos.",
                    "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Convertimos los textos de los goles a números enteros
            int golesLocal = Integer.parseInt(txtGoles1.getText().trim());
            int golesVisitante = Integer.parseInt(txtGoles2.getText().trim());

            // Validación 3: Evitar números negativos de goles
            if (golesLocal < 0 || golesVisitante < 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La cantidad de goles no puede ser un número negativo.",
                        "Error de Datos", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. BUSCAMOS LAS ENTIDADES EQUIPO EN LA LISTA DEL SERVICIO
            Entities.Equipo equipoLocal = null;
            Entities.Equipo equipoVisitante = null;

            for (Entities.Equipo eq : servicio.getEquipos()) {
                if (eq.getNombre().equals(nombreLocal)) {
                    equipoLocal = eq;
                }
                if (eq.getNombre().equals(nombreVisitante)) {
                    equipoVisitante = eq;
                }
            }

            // 4. Si encontramos las referencias, creamos el Partido y lo guardamos en el archivo real
            if (equipoLocal != null && equipoVisitante != null) {
                Entities.Partido nuevoPartido = new Entities.Partido(equipoLocal, equipoVisitante, golesLocal, golesVisitante);

                // Aquí el servicio procesa los puntos, goles y reescribe el archivo .properties
                servicio.registrarResultado(nuevoPartido);

                // Mensaje informativo real de éxito
                javax.swing.JOptionPane.showMessageDialog(this,
                        "¡Partido registrado con éxito!\nLos datos se guardaron en el archivo.",
                        "Registro Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // 5. Regresamos a la ventana principal
                VentanaPrincipal principal = new VentanaPrincipal();
                principal.setLocationRelativeTo(null);
                principal.setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error interno: No se pudieron mapear las instancias de los equipos.",
                        "Error de Mapeo", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, ingresa solo números enteros válidos en los campos de goles.",
                    "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            // Captura los errores de validación de tu negocio
            javax.swing.JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Validación de Campeonato", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEquipoActionPerformed
        VentanaRegistrarEquipo registrarEquipo = new VentanaRegistrarEquipo();
        registrarEquipo.setVisible(true);
        this.dispose(); // Cierra el formulario de partidos
    }//GEN-LAST:event_btnRegistrarEquipoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Deseas salir de FutMJI?",
            "Cerrar Aplicación", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra por completo la máquina virtual de Java de forma limpia
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRegistrarPartido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrarEquipo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbEquipo1;
    private javax.swing.JComboBox<String> cbEquipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtGoles1;
    private javax.swing.JTextField txtGoles2;
    // End of variables declaration//GEN-END:variables
}
