/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Services.ServicioCampeonato;
import java.awt.Image;
import javax.swing.ImageIcon;

public class VentanaRegistrarEquipo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistrarEquipo.class.getName());

    /**
     * Creates new form VentanaRegistrarEquipo
     */
    private ServicioCampeonato servicio;

    public VentanaRegistrarEquipo() {
        // Inicializamos el servicio de datos
        this.servicio = new ServicioCampeonato();

        // Inicializa el diseño que armaste en los pasos anteriores
        initComponents();

        // Centra la ventana en medio de la pantalla al abrirse
        this.setLocationRelativeTo(null);

        // Pone el icono del jugador de fútbol en la barra nativa de Windows
        try {
            java.net.URL urlIcono = getClass().getResource("/Vista/logo.png");
            if (urlIcono != null) {
                ImageIcon icon = new ImageIcon(urlIcono);
                setIconImage(icon.getImage());
            }
        } catch (Exception e) {
            System.out.println("No se pudo colocar el icono en la cabecera: " + e.getMessage());
        }
        colocarLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRegistrarPartido = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelFormulario = new javax.swing.JPanel();
        lblTituloAccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        cmbTipoEquipo = new javax.swing.JComboBox<>();
        lblDatoEspecifico = new javax.swing.JLabel();
        txtDatoEspecifico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FutMJI -  REGISTRAR EQUIPO");

        panelPrincipal.setBackground(new java.awt.Color(245, 246, 250));

        panelMenu.setBackground(new java.awt.Color(25, 42, 86));

        btnInicio.setBackground(new java.awt.Color(25, 42, 86));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(204, 204, 204));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnRegistrarPartido.setBackground(new java.awt.Color(25, 42, 86));
        btnRegistrarPartido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarPartido.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrarPartido.setText("Registrar Partido");
        btnRegistrarPartido.setBorder(null);
        btnRegistrarPartido.setBorderPainted(false);
        btnRegistrarPartido.setContentAreaFilled(false);
        btnRegistrarPartido.addActionListener(this::btnRegistrarPartidoActionPerformed);

        btnSalir.setBackground(new java.awt.Color(25, 42, 86));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Cerrar sesion");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnRegistrarPartido)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(21, 21, 21))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnInicio)
                .addGap(71, 71, 71)
                .addComponent(btnRegistrarPartido)
                .addGap(65, 65, 65)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFormulario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTituloAccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloAccion.setForeground(new java.awt.Color(25, 42, 86));
        lblTituloAccion.setText("REGISTRAR NUEVO EQUIPO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 46, 86));
        jLabel1.setText("Nombre del Equipo");

        txtNombreEquipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(25, 42, 86));
        btnGuardar.setText("Guardar Equipo");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        cmbTipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Internacional" }));
        cmbTipoEquipo.addActionListener(this::cmbTipoEquipoActionPerformed);

        lblDatoEspecifico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatoEspecifico.setForeground(new java.awt.Color(25, 42, 86));
        lblDatoEspecifico.setText("Departamento");

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTituloAccion))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnGuardar))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblDatoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFormularioLayout.createSequentialGroup()
                                .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblTituloAccion)))
                .addGap(18, 18, 18)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnGuardar)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void colocarLogo() {
        try {
            // 1. Buscamos la ruta del logo dentro del paquete Vista
            java.net.URL stream = getClass().getResource("/Vista/logo.png");

            if (stream != null) {
                ImageIcon imagenOriginal = new ImageIcon(stream);

                // 2. Tomamos el ancho y alto del lblLogo que pusiste en el diseño
                int ancho = lblLogo.getWidth();
                int alto = lblLogo.getHeight();

                // Valores de respaldo si el layout aún no ha calculado las dimensiones
                if (ancho == 0 || alto == 0) {
                    ancho = 130; // Ajusta este valor al ancho aproximado de tu cuadro naranja
                    alto = 82;   // Ajusta este valor al alto aproximado de tu cuadro naranja
                }

                // 3. Redimensionamos la imagen de forma suave (Smooth)
                Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                ImageIcon logoFinal = new ImageIcon(imagenEscalada);

                // 4. Se lo asignamos al componente y refrescamos
                lblLogo.setIcon(logoFinal);
                lblLogo.repaint();
            } else {
                System.out.println("No se pudo encontrar el archivo logo.png en el paquete Vista.");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar el logo en el panel: " + e.getMessage());
        }
    }
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal();
        principal.setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombreEquipo = txtNombreEquipo.getText().trim();
        String datoEspecifico = txtDatoEspecifico.getText().trim();
        String tipoEquipo = cmbTipoEquipo.getSelectedItem().toString();

        // 1. Validar campos vacíos
        if (nombreEquipo.isEmpty() || datoEspecifico.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, completa todos los campos del formulario.",
                    "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Validar que no exista otro equipo igual
            for (Entities.Equipo eq : servicio.getEquipos()) { // Asegúrate de usar 'controlador' o 'servicio' según tu variable
                if (eq.getNombre().equalsIgnoreCase(nombreEquipo)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ya existe un equipo registrado con el nombre: " + nombreEquipo,
                            "Equipo Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // 3. ¡APLICACIÓN DE HERENCIA Y POLIMORFISMO!
            Entities.Equipo nuevoEquipo; // Declaramos la clase padre

            if (tipoEquipo.equals("Nacional")) {
                // Instanciamos la clase hija EquipoNacional
                nuevoEquipo = new Entities.EquipoNacional(nombreEquipo, datoEspecifico);
            } else {
                // Instanciamos la clase hija EquipoInternacional
                nuevoEquipo = new Entities.EquipoInternacional(nombreEquipo, datoEspecifico);
            }

            // 4. Se envía al servicio (él se encargará de guardarlo polimórficamente en el properties)
            servicio.registrarEquipo(nuevoEquipo);

            // 5. Notificar éxito
            javax.swing.JOptionPane.showMessageDialog(this,
                    "¡" + tipoEquipo + " '" + nombreEquipo + "' registrado con éxito!",
                    "Registro Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // 6. Limpiar campos por si quiere registrar otro de inmediato
            txtNombreEquipo.setText("");
            txtDatoEspecifico.setText("");
            cmbTipoEquipo.setSelectedIndex(0);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar: " + ex.getMessage(),
                    "Error del Sistema", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegistrarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPartidoActionPerformed
        VentanaRegistrarPartido registrarPartido = new VentanaRegistrarPartido();
        registrarPartido.setVisible(true);
        this.dispose(); // Cierra el formulario de equipos
    }//GEN-LAST:event_btnRegistrarPartidoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Deseas salir de FutMJI?",
                "Cerrar Aplicación", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra por completo la máquina virtual de Java de forma limpia
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbTipoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEquipoActionPerformed
        String tipoSeleccionado = cmbTipoEquipo.getSelectedItem().toString();

        if (tipoSeleccionado.equals("Nacional")) {
            lblDatoEspecifico.setText("Departamento:");
        } else {
            lblDatoEspecifico.setText("País:");
        }
    }//GEN-LAST:event_cmbTipoEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Activamos el Look and Feel moderno de FlatLaf Light
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "No se pudo iniciar FlatLaf", ex);
        }

        /* Creamos y mostramos la ventana */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaRegistrarEquipo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrarPartido;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDatoEspecifico;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloAccion;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtDatoEspecifico;
    private javax.swing.JTextField txtNombreEquipo;
    // End of variables declaration//GEN-END:variables
}
